name: CD
on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Begin CD...
              uses: actions/checkout@v2

            - name: Use Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install deps (with cache)
              uses: bahmutov/npm-install@v1

            - name: Building...
              run: npm run build

            - name: Publishing to github-pages
              run: |
                  git config --global user.name $user_name
                  git config --global user.email $user_email
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  npm run push-gh-pages
              working-directory: ./docs
              env:
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
                  NODE_ENV: 'production'
