name: CD
on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Begin CD...
              uses: actions/checkout@v2

            - name: Use Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install deps (with cache)
              uses: bahmutov/npm-install@v1

            - name: Building...
              run: npm run build

            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: git@github.com:owner/repo.git
                BRANCH: gh-pages
                FOLDER: build
                SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}

